# Generated by Django 5.0.3 on 2024-04-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='count_of_views',
            new_name='views',
        ),
    ]
