# Generated by Django 4.2 on 2024-05-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('created_at',), 'permissions': [('can_change_blogpost_title', 'Can change title of blogpost'), ('can_change_blogpost_content', 'Can change content of blogpost'), ('can_change_blogpost_preview', 'Can change preview of blogpost'), ('can_change_blogpost_is_published_status', 'Can change publication status of blogpost')], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
