# Generated by Django 5.0.3 on 2024-04-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_of_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
